# Generated by Django 4.1.5 on 2023-01-14 22:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tg_username', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('discord_username', models.CharField(blank=True, max_length=32, null=True)),
                ('referrals', models.IntegerField(default=0)),
                ('task_sum', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('wallet', models.CharField(blank=True, max_length=250, null=True)),
                ('referral_link', models.UUIDField(default=uuid.uuid4)),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_handler.client')),
            ],
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('image_answer', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('success_text', models.TextField()),
                ('fail_text', models.TextField()),
                ('proof_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_sum', models.DecimalField(decimal_places=2, max_digits=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot_handler.client')),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_handler.client')),
                ('proof', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_handler.proof')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_handler.task')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='tasks',
            field=models.ManyToManyField(through='bot_handler.UserTask', to='bot_handler.task'),
        ),
    ]
