# Generated by Django 4.1.5 on 2023-01-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Task name', max_length=30),
        ),
    ]
