# Generated by Django 4.1.5 on 2023-01-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0002_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_min_amount', models.DecimalField(decimal_places=2, default=5, max_digits=30)),
                ('referral_cost', models.DecimalField(decimal_places=2, default=0.15, max_digits=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
