# Generated by Django 4.1.5 on 2023-01-20 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0004_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='welcome_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawalorder',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='withdrawalorder',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
