# Generated by Django 4.1.5 on 2023-01-28 23:18

import bot_handler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0006_alter_proof_image_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='image_answer',
            field=models.ImageField(blank=True, null=True, upload_to=bot_handler.models.image_folder),
        ),
    ]
