# Generated by Django 4.1.5 on 2023-02-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0008_validator_remove_client_referral_link_task_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='need_validation',
            field=models.BooleanField(default=False),
        ),
    ]
