# Generated by Django 4.1.5 on 2023-02-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0009_task_need_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='expression',
            field=models.TextField(),
        ),
    ]
