# Generated by Django 4.1.5 on 2023-02-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0010_alter_validator_expression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='proof_type',
            field=models.CharField(choices=[('text', 'text'), ('photo', 'photo')], max_length=20),
        ),
    ]
