# Generated by Django 4.1.5 on 2023-03-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0011_alter_task_proof_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_verified_referral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='unverified_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
