# Generated by Django 4.1.5 on 2023-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0012_client_is_verified_referral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='proof_exists',
            field=models.BooleanField(default=False),
        ),
    ]
