# Generated by Django 4.1.5 on 2023-03-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0013_usertask_proof_exists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('chain', models.CharField(default=None, max_length=30)),
                ('hash', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TokenPrice',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='repeatable',
            field=models.BooleanField(default=False),
        ),
    ]
