# Generated by Django 4.1.5 on 2023-03-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0015_storedtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='need_trx_proof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='trx_proof_chain',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
