# Generated by Django 4.1.5 on 2023-03-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0016_task_need_trx_proof_task_trx_proof_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenprice',
            name='price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
    ]
