# Generated by Django 4.1.5 on 2023-03-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0017_alter_tokenprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='chain',
            field=models.CharField(choices=[('BSC', 'BSC'), ('ETH', 'ETH'), ('POLYGON', 'POLYGON')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='trx_proof_chain',
            field=models.CharField(blank=True, choices=[('BSC', 'BSC'), ('ETH', 'ETH'), ('POLYGON', 'POLYGON')], max_length=20, null=True),
        ),
    ]
