# Generated by Django 4.1.5 on 2023-03-18 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0018_alter_contract_chain_alter_task_trx_proof_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_handler.validator'),
        ),
    ]
