# Generated by Django 4.1.5 on 2023-04-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_handler', '0019_alter_task_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_proof_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
